### ISSUE TITLE
تگ یا دسته بندی 

### ISSUE THREAD

**Issue by HarlyquinForest** [linux98ir/linux98ir.github.io#2]
به نظر میاد تو جکیل تگ  و دسته بندی هر دو یه چیزن شایدم نیستن 

من با توانایی های شگف انگیزم در زمینه وب نتونستم راش بندازم  . تست کن ببین میشه اوکیش کرد ؟

**Comment by akamohebbi** [comment]
نه خب تفاوت های دارن
دیشب اوکی شد و الان بالاست و کار می کنه
